fix: cannot set HttpURLConnection request properties after a response
java.net.ProtocolException: Connection already established

notes:
* this issue was introduced by the commit to:
  automatically follow redirects for all HTTP 3xx codes
* in order to do so, the response code needs to be inspected
* as such, the HttpURLConnection returned by getConnection()
  has already been established,
  and its request properties cannot be changed